/* Small, dependency-free shared free-ride server. Node 18+. */
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const sessions=new Map(),root=__dirname,port=Number(process.env.PORT)||8080;
const marketFile=process.env.MARKET_DATA_FILE||path.join(root,'market-data.json');
let market={listings:[],accounts:{}};try{market=JSON.parse(fs.readFileSync(marketFile,'utf8'));}catch{}
function storeMarket(){fs.writeFileSync(marketFile,JSON.stringify(market));}
function marketAction(input,res){const token=String(input.token||'');if(!/^[a-zA-Z0-9-]{24,100}$/.test(token))return json(res,400,{error:'Missing marketplace identity'});
const account=market.accounts[token]||(market.accounts[token]={receipts:[],requests:{}});const action=input.action;
if(action==='list')return json(res,200,{listings:market.listings.map(l=>({...l,token:undefined,mine:l.token===token})),receipts:account.receipts});
const request=String(input.request||'');if(!/^[a-zA-Z0-9-]{10,100}$/.test(request))return json(res,400,{error:'Missing transaction identity'});if(account.requests[request])return json(res,200,account.requests[request]);
let result={ok:true};
if(action==='sell'){const h=input.horse,price=Number(input.price);if(!h||typeof h.name!=='string'||!Number.isSafeInteger(price)||price<1||price>1000000000||!['speed','jump','stamina','temperament','maxJumpCm'].every(k=>Number.isFinite(h[k])&&h[k]>=0))return json(res,400,{error:'Invalid horse or price'});if(market.listings.length>=300)return json(res,409,{error:'Marketplace full'});if(market.listings.some(l=>l.token===token&&l.original===h.id))return json(res,409,{error:'Horse already listed'});const listing={id:crypto.randomUUID(),token,original:h.id,seller:String(input.name||'Rider').slice(0,24),horse:{...h,name:h.name.slice(0,40)},price};market.listings.push(listing);result.listing=listing.id;
}else if(action==='buy'||action==='cancel'){const index=market.listings.findIndex(l=>l.id===input.listing);if(index<0)return json(res,409,{error:'This horse is no longer available'});const l=market.listings[index];if(action==='cancel'&&l.token!==token)return json(res,403,{error:'This is not your listing'});if(action==='buy'&&l.token===token)return json(res,400,{error:'Use Withdraw for your own horse'});if(action==='buy'&&(!Number.isSafeInteger(input.balance)||input.balance<l.price))return json(res,400,{error:'Not enough coins'});const horse={...l.horse,id:'online-'+crypto.randomUUID(),origin:'online',price:l.price};account.receipts.push({id:crypto.randomUUID(),horse,cost:action==='buy'?l.price:0});if(action==='buy')market.accounts[l.token].receipts.push({id:crypto.randomUUID(),coins:l.price,horseName:l.horse.name});market.listings.splice(index,1);
}else return json(res,400,{error:'Unknown marketplace action'});
account.requests[request]=result;storeMarket();return json(res,200,result);}
const allowed=new Set(['index.html','style.css','horse-jumps.js','horse-catalogue.js','renderer-webgl.js','character-models.js','venue-krc.js','course-designs.js','game.js']);
function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'});res.end(JSON.stringify(body));}
function tidy(){const now=Date.now();for(const [id,s]of sessions)if(now-s.seen>15000)sessions.delete(id);}
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}const url=new URL(req.url,'http://localhost');if(req.method==='POST'&&url.pathname.startsWith('/api/')){try{let body='',bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>8192){json(res,413,{error:'Request too large'});req.destroy();return;}body+=chunk;}const input=JSON.parse(body);tidy();if(url.pathname==='/api/market')return marketAction(input,res);if(url.pathname==='/api/lobbies')return json(res,200,{count:[...sessions.values()].filter(s=>s.room==='PUBLIC').length,max:16});if(url.pathname==='/api/join'){const room=String(input.room||'KRC').trim().toUpperCase();if(!/^[A-Z0-9-]{1,24}$/.test(room))return json(res,400,{error:'Use 1–24 letters, numbers or dashes for the room.'});if(sessions.size>=128||[...sessions.values()].filter(s=>s.room===room).length>=16)return json(res,409,{error:'Server or room is full.'});const id=crypto.randomUUID();sessions.set(id,{room,name:String(input.name||'Rider').trim().slice(0,24)||'Rider',seen:Date.now(),state:null});return json(res,200,{id,room});}const session=sessions.get(input.id);if(!session)return json(res,401,{error:'Session expired. Join again.'});if(url.pathname==='/api/leave'){sessions.delete(input.id);return json(res,200,{ok:true});}if(url.pathname==='/api/state'){const p=input.state||{},state={};for(const k of ['x','z','a','speed','gait','energy','y','jumpT','phase']){if(!Number.isFinite(p[k]))return json(res,400,{error:'Invalid rider position'});state[k]=p[k];}state.x=Math.max(-185,Math.min(232,state.x));state.z=Math.max(-100,Math.min(115,state.z));state.y=Math.max(0,Math.min(10,state.y));state.gait=Math.max(1,Math.min(4,Math.round(state.gait)));state.size=Number.isFinite(p.size)?Math.max(.4,Math.min(2,p.size)):1;state.coat=/^#[0-9a-f]{6}$/i.test(p.coat)?p.coat:'#89553d';state.riderFallen=!!p.riderFallen;state.tacked=p.tacked!==false;session.state=state;session.seen=Date.now();return json(res,200,{peers:[...sessions.entries()].filter(([id,s])=>id!==input.id&&s.room===session.room&&s.state).map(([id,s])=>({id,name:s.name,...s.state}))});}return json(res,404,{error:'Unknown action'});}catch(e){return json(res,400,{error:'Invalid request'});}}
if(req.method==='GET'){const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(allowed.has(name)){res.writeHead(200,{'Content-Type':name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':'application/javascript'});return fs.createReadStream(path.join(root,name)).pipe(res);}}res.writeHead(404);res.end('Not found');});
server.on('error',error=>{console.error('Unable to start the multiplayer server: '+error.message);process.exitCode=1;});
server.listen(port,'0.0.0.0',()=>console.log(`STRIDE multiplayer: http://localhost:${port} — share your computer's LAN IP with friends on the same network.`));
