/* Smooth lighting, distance haze and directional soft shadows; Canvas fallback remains. */
(() => {
'use strict';
const norm=v=>{const d=Math.hypot(...v)||1;return v.map(x=>x/d);},dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function multiply(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function view(eye,target){const b=norm(eye.map((x,i)=>x-target[i])),r=norm(cross([0,1,0],b)),u=cross(b,r);return new Float32Array([r[0],u[0],b[0],0,r[1],u[1],b[1],0,r[2],u[2],b[2],0,-dot(r,eye),-dot(u,eye),-dot(b,eye),1]);}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),d=near-far;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/d,-1,0,0,2*far*near/d,0]);}
const ortho=new Float32Array([1/155,0,0,0,0,1/155,0,0,0,0,-2/399,0,0,0,-401/399,1]);
const lightMatrix=multiply(ortho,view([105,180,-95],[0,0,0])),palette=new Map();
function rgb(c){if(palette.has(c))return palette.get(c);let a;if(c[0]==='#'){const n=parseInt(c.slice(1,7),16);a=[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255];}else{a=c.match(/[\d.]+/g).slice(0,3).map(x=>Number(x)/255);}palette.set(c,a);return a;}
function mesh(faces){const values=[];for(const f of faces){if(f.shadow)continue;const color=rgb(f.materialColor||f.c),n=f.ground?[0,1,0]:norm(cross(f.v[1].map((x,i)=>x-f.v[0][i]),f.v[2].map((x,i)=>x-f.v[0][i])));for(let i=1;i<f.v.length-1;i++)for(const j of [0,i,i+1])values.push(...f.v[j],...(f.normals?.[j]||n),...color,f.ground?2:f.character?1:0);}return new Float32Array(values);}
const vertex=`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec3 aColor;attribute float aKind;uniform mat4 uViewProjection;uniform mat4 uLight;varying vec3 vPosition;varying vec3 vNormal;varying vec3 vColor;varying float vKind;varying vec4 vShadow;void main(){vPosition=aPosition;vNormal=aNormal;vColor=aColor;vKind=aKind;vShadow=uLight*vec4(aPosition,1.0);gl_Position=uViewProjection*vec4(aPosition,1.0);}`;
const fragment=`precision highp float;varying vec3 vPosition;varying vec3 vNormal;varying vec3 vColor;varying float vKind;varying vec4 vShadow;uniform vec3 uEye;uniform sampler2D uShadow;float unpack(vec4 x){return dot(x,vec4(1.0/16777216.0,1.0/65536.0,1.0/256.0,1.0));}float noise(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float shadow(vec3 n){vec3 p=vShadow.xyz/vShadow.w*.5+.5;if(p.x<0.0||p.x>1.0||p.y<0.0||p.y>1.0||p.z>1.0)return 1.0;float bias=max(.0012,.003*(1.0-dot(n,normalize(vec3(.5,.85,-.45)))));float s=0.0;for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=unpack(texture2D(uShadow,p.xy+vec2(float(x),float(y))/1024.0));s+=p.z-bias>d?.38:1.0;}return s/9.0;}void main(){vec3 n=normalize(vNormal),l=normalize(vec3(.5,.85,-.45)),v=normalize(uEye-vPosition),h=normalize(l+v);float diffuse=max(0.0,dot(n,l)),s=shadow(n);vec3 base=vColor;float grain=noise(vPosition.xz*(vKind>1.5?24.0:48.0));base*=1.0+(grain-.5)*(vKind>1.5?.075:.018);float gloss=vKind>.5&&vKind<1.5?pow(max(0.0,dot(n,h)),34.0)*.12:0.0;vec3 color=base*(.44+.69*diffuse*s)+vec3(1.0,.87,.70)*gloss*s;float fog=1.0-exp(-pow(length(uEye-vPosition)/195.0,2.0));color=mix(color,vec3(.89,.85,.74),min(.87,fog));gl_FragColor=vec4(color,1.0);}`;
const depthVertex=`attribute vec3 aPosition;uniform mat4 uViewProjection;void main(){gl_Position=uViewProjection*vec4(aPosition,1.0);}`;
const depthFragment=`precision highp float;void main(){vec4 r=fract(gl_FragCoord.z*vec4(16777216.0,65536.0,256.0,1.0));r-=r.xxyz*vec4(0.0,1.0/256.0,1.0/256.0,1.0/256.0);gl_FragColor=r;}`;
const skyVertex=`attribute vec2 aPosition;varying float vY;void main(){vY=aPosition.y*.5+.5;gl_Position=vec4(aPosition,0.0,1.0);}`;
const skyFragment=`precision mediump float;varying float vY;void main(){gl_FragColor=vec4(mix(vec3(.90,.86,.75),vec3(.45,.68,.80),clamp(vY,0.0,1.0)),1.0);}`;
window.createStrideGpu=canvas=>{let gl;try{gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)return null;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function program(v,f){const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
const main=program(vertex,fragment),depth=program(depthVertex,depthFragment),sky=program(skyVertex,skyFragment),staticBuffer=gl.createBuffer(),dynamicBuffer=gl.createBuffer(),skyBuffer=gl.createBuffer();let staticCount=0,staticSource=null;
gl.bindBuffer(gl.ARRAY_BUFFER,skyBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);
const shadowTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,shadowTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1024,1024,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
const framebuffer=gl.createFramebuffer(),depthBuffer=gl.createRenderbuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,shadowTexture,0);gl.bindRenderbuffer(gl.RENDERBUFFER,depthBuffer);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,1024,1024);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,depthBuffer);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Shadow framebuffer unavailable');gl.bindFramebuffer(gl.FRAMEBUFFER,null);
function attributes(p,buffer,full){for(let i=0;i<gl.getParameter(gl.MAX_VERTEX_ATTRIBS);i++)gl.disableVertexAttribArray(i);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const [name,size,offset] of [['aPosition',3,0],['aNormal',3,12],['aColor',3,24],['aKind',1,36]]){const location=gl.getAttribLocation(p,name);if(location>=0){gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,size,gl.FLOAT,false,40,offset);}}}
function drawBoth(p,full,dynamicCount){attributes(p,staticBuffer,full);gl.drawArrays(gl.TRIANGLES,0,staticCount);attributes(p,dynamicBuffer,full);gl.drawArrays(gl.TRIANGLES,0,dynamicCount);}
return {render(staticFaces,dynamicFaces,cam,width,height){if(staticSource!==staticFaces){const data=mesh(staticFaces);gl.bindBuffer(gl.ARRAY_BUFFER,staticBuffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);staticCount=data.length/10;staticSource=staticFaces;}const dynamic=mesh(dynamicFaces);gl.bindBuffer(gl.ARRAY_BUFFER,dynamicBuffer);gl.bufferData(gl.ARRAY_BUFFER,dynamic,gl.DYNAMIC_DRAW);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.viewport(0,0,1024,1024);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(depth);gl.uniformMatrix4fv(gl.getUniformLocation(depth,'uViewProjection'),false,lightMatrix);drawBoth(depth,false,dynamic.length/10);
gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.DEPTH_TEST);gl.useProgram(sky);for(let i=0;i<gl.getParameter(gl.MAX_VERTEX_ATTRIBS);i++)gl.disableVertexAttribArray(i);gl.bindBuffer(gl.ARRAY_BUFFER,skyBuffer);const pos=gl.getAttribLocation(sky,'aPosition');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,8,0);gl.drawArrays(gl.TRIANGLES,0,3);gl.enable(gl.DEPTH_TEST);gl.useProgram(main);const eye=[cam.x,cam.y,cam.z],target=[cam.tx,cam.ty,cam.tz],focal=Math.min(width,height)*1.18,matrix=multiply(perspective(2*Math.atan(height/(2*focal)),width/height,.25,480),view(eye,target));gl.uniformMatrix4fv(gl.getUniformLocation(main,'uViewProjection'),false,matrix);gl.uniformMatrix4fv(gl.getUniformLocation(main,'uLight'),false,lightMatrix);gl.uniform3fv(gl.getUniformLocation(main,'uEye'),eye);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,shadowTexture);gl.uniform1i(gl.getUniformLocation(main,'uShadow'),0);drawBoth(main,true,dynamic.length/10);},gl};
}catch(error){console.warn('GPU renderer unavailable; using Canvas.',error.message);return null;}};
})();
